volumes:
    db_data:

networks:
    local-srv-network:
        name: local-srv-network
        driver: bridge
    central-srv-network:
        name: central-srv-network
        driver: bridge

services:
    postgres:
        container_name: postgres
        build:
            context: ./build/postgres/
            dockerfile: ./Dockerfile
        ports:
            - 5432:5432
        volumes:
            - db_data:/var/lib/postgresql/data
            - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=database
        networks:
            - local-srv-network
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
    nats:
        container_name: nats
        image: nats:2.10-alpine
        command:
            # - "--cluster"
            # - "nats://0.0.0.0:6222"
            - "--http_port"
            - "8222"
            - "--port"
            - "4222"
            - "--js"
            - "--debug"
        ports:
            - "8222:8222"
            - "6222:6222"
            - "4222:4222"
        networks:
            - local-srv-network
            - central-srv-network
        healthcheck:
            test: ["CMD-SHELL", "wget http://localhost:8222/healthz -q -S -O -"]
            interval: 5s
            timeout: 5s
            retries: 5

    local:
        container_name: local
        build:
            context: ./
            dockerfile: ./build/local/Dockerfile
        restart: always
        environment:
            - LISTEN_PORT=8000
            - DB_URL=host=postgres user=postgres password=postgres dbname=database sslmode=disable
        networks:
            - local-srv-network
        depends_on:
            postgres:
                condition: service_healthy
            nats:
                condition: service_healthy
            transaction_logger:
                condition: service_healthy
        healthcheck:
            test: ["CMD-SHELL", "wget http://localhost:8000/health -q -S -O -"]
            interval: 5s
            timeout: 5s
            retries: 5

    central:
        container_name: central
        build:
            context: ./
            dockerfile: ./build/central/Dockerfile
        restart: always
        environment:
            - NATS_URL=nats://nats:4222
            - LISTEN_PORT=8000
        networks:
            - central-srv-network
        depends_on:
            postgres:
                condition: service_healthy
            nats:
                condition: service_healthy
        healthcheck:
            test: ["CMD-SHELL", "wget http://localhost:8000/health -q -S -O -"]
            interval: 5s
            timeout: 5s
            retries: 5

    transaction_logger:
        container_name: transaction_logger
        image: ihippik/wal-listener:v2.7.1
        volumes:
            - ./wal-listener.yml:/app/config.yml
        networks:
            - local-srv-network
        depends_on:
            postgres:
                condition: service_healthy
            nats:
                condition: service_healthy
        healthcheck:
            # TODO: no wget/curl on wal-listener image, maybe create our own image and fork
            # test: ["CMD-SHELL", "wget http://localhost:8000/healthz -q -S -O -"]
            test: ["CMD-SHELL", "exit 0"] # NO-OP
            interval: 5s
            timeout: 5s
            retries: 5
