volumes:
    catalog_data:
    nats_data:

services:
    nats:
        image: nats:alpine
        ports:
            - "4222:4222"
        command:
            - "--jetstream"
            - "--store_dir=/data/jetstream"
        volumes:
            - nats_data:/data/jetstream
        healthcheck:
            test: ["CMD-SHELL", "wget http://localhost:8222/healthz -q -S -O -"]
            interval: 1s
            timeout: 5s
            retries: 5

    catalog:
        build: { args: { SERVICE: catalog } }
        environment:
            - DB_URL=postgres://catalog:catalog@catalog-postgres:5432/catalog
            - NATS_URL=nats://nats:4222
            - OTLP_URL=collector:4317
        depends_on:
            - catalog-postgres
            - nats
            - collector
    catalog-postgres:
        image: postgres:alpine
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=catalog
            - POSTGRES_PASSWORD=catalog
        volumes:
            - ./srv/catalog/schema.sql:/docker-entrypoint-initdb.d/schema.sql
            - catalog_data:/var/lib/postgresql/data

    order:
        build: { args: { SERVICE: order } }
        environment:
            - NATS_URL=nats://nats:4222
            - OTLP_URL=collector:4317
        depends_on:
            - nats
            - collector

    warehouse:
        build: { args: { SERVICE: warehouse } }
        environment:
            - WAREHOUSE_ID=41
            - NATS_URL=nats://nats:4222
            - OTLP_URL=collector:4317
        depends_on:
            - nats
            - collector

    # Observability stack
    collector:
        image: otel/opentelemetry-collector-contrib
        ports:
            - "4317:4317"
        volumes:
            - ./containers/collector.yml:/etc/otelcol-contrib/config.yaml:ro
    loki:
        image: grafana/loki:3.3.1
    prometheus:
        image: prom/prometheus
        ports:
            - "9090:9090"
        command:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--web.enable-otlp-receiver"
    grafana:
        image: grafana/grafana
        ports:
            - "3000:3000"
        volumes:
            - ./containers/grafana:/etc/grafana/provisioning/
